#!/bin/bash

case "$1" in
    "on") #we're running hcwm as our primary wm
	hsetroot -fill ~/Xwalls/stockings.jpg
	;;
    "off") #we're leaving hcwm, returning to default wm
	hsetroot -fill ~/Xwalls/abstract.jpg
	;;
    *) # We broke something. OH NO!!!
esac
